# Generated by Django 3.1.4 on 2021-01-02 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='access_users',
            field=models.ManyToManyField(related_name='access_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
