# Generated by Django 3.2.6 on 2021-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210907_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='ASDFGth', max_length=255),
            preserve_default=False,
        ),
    ]
