# Generated by Django 3.1.5 on 2021-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_answer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
